// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kaixin.proto

package aimgo_passport_http2_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HahaRequest struct {
	//	请求名称
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HahaRequest) Reset()         { *m = HahaRequest{} }
func (m *HahaRequest) String() string { return proto.CompactTextString(m) }
func (*HahaRequest) ProtoMessage()    {}
func (*HahaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c91fc70a7d1b2a5, []int{0}
}

func (m *HahaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HahaRequest.Unmarshal(m, b)
}
func (m *HahaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HahaRequest.Marshal(b, m, deterministic)
}
func (m *HahaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HahaRequest.Merge(m, src)
}
func (m *HahaRequest) XXX_Size() int {
	return xxx_messageInfo_HahaRequest.Size(m)
}
func (m *HahaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HahaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HahaRequest proto.InternalMessageInfo

func (m *HahaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HahaResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HahaResponse) Reset()         { *m = HahaResponse{} }
func (m *HahaResponse) String() string { return proto.CompactTextString(m) }
func (*HahaResponse) ProtoMessage()    {}
func (*HahaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c91fc70a7d1b2a5, []int{1}
}

func (m *HahaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HahaResponse.Unmarshal(m, b)
}
func (m *HahaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HahaResponse.Marshal(b, m, deterministic)
}
func (m *HahaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HahaResponse.Merge(m, src)
}
func (m *HahaResponse) XXX_Size() int {
	return xxx_messageInfo_HahaResponse.Size(m)
}
func (m *HahaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HahaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HahaResponse proto.InternalMessageInfo

func (m *HahaResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HahaResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *HahaResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type KaixinRequest struct {
	//	请求名称
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KaixinRequest) Reset()         { *m = KaixinRequest{} }
func (m *KaixinRequest) String() string { return proto.CompactTextString(m) }
func (*KaixinRequest) ProtoMessage()    {}
func (*KaixinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c91fc70a7d1b2a5, []int{2}
}

func (m *KaixinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KaixinRequest.Unmarshal(m, b)
}
func (m *KaixinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KaixinRequest.Marshal(b, m, deterministic)
}
func (m *KaixinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KaixinRequest.Merge(m, src)
}
func (m *KaixinRequest) XXX_Size() int {
	return xxx_messageInfo_KaixinRequest.Size(m)
}
func (m *KaixinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KaixinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KaixinRequest proto.InternalMessageInfo

func (m *KaixinRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KaixinResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KaixinResponse) Reset()         { *m = KaixinResponse{} }
func (m *KaixinResponse) String() string { return proto.CompactTextString(m) }
func (*KaixinResponse) ProtoMessage()    {}
func (*KaixinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c91fc70a7d1b2a5, []int{3}
}

func (m *KaixinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KaixinResponse.Unmarshal(m, b)
}
func (m *KaixinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KaixinResponse.Marshal(b, m, deterministic)
}
func (m *KaixinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KaixinResponse.Merge(m, src)
}
func (m *KaixinResponse) XXX_Size() int {
	return xxx_messageInfo_KaixinResponse.Size(m)
}
func (m *KaixinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KaixinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KaixinResponse proto.InternalMessageInfo

func (m *KaixinResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *KaixinResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *KaixinResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*HahaRequest)(nil), "aimgo.passport.http2.v1.HahaRequest")
	proto.RegisterType((*HahaResponse)(nil), "aimgo.passport.http2.v1.HahaResponse")
	proto.RegisterType((*KaixinRequest)(nil), "aimgo.passport.http2.v1.KaixinRequest")
	proto.RegisterType((*KaixinResponse)(nil), "aimgo.passport.http2.v1.KaixinResponse")
}

func init() { proto.RegisterFile("kaixin.proto", fileDescriptor_3c91fc70a7d1b2a5) }

var fileDescriptor_3c91fc70a7d1b2a5 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4e, 0xcc, 0xac,
	0xc8, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4f, 0xcc, 0xcc, 0x4d, 0xcf, 0xd7,
	0x2b, 0x48, 0x2c, 0x2e, 0x2e, 0xc8, 0x2f, 0x2a, 0xd1, 0xcb, 0x28, 0x29, 0x29, 0x30, 0xd2, 0x2b,
	0x33, 0x54, 0x52, 0xe4, 0xe2, 0xf6, 0x48, 0xcc, 0x48, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x95, 0x3c, 0xb8, 0x78, 0x20, 0x4a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x41, 0x6a, 0x92,
	0xf3, 0x53, 0x20, 0x6a, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09,
	0x26, 0xb0, 0x36, 0x10, 0x13, 0xa4, 0x2a, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x19, 0x62, 0x12, 0x88,
	0xad, 0xa4, 0xcc, 0xc5, 0xeb, 0x0d, 0x76, 0x15, 0x3e, 0xeb, 0xbc, 0xb8, 0xf8, 0x60, 0x8a, 0x28,
	0xb5, 0xd0, 0x28, 0x07, 0x66, 0x61, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x34, 0x17,
	0x1b, 0x44, 0x40, 0x48, 0x4d, 0x0f, 0x47, 0x90, 0xe8, 0xa1, 0x38, 0x51, 0x4a, 0x9d, 0xa0, 0x3a,
	0x88, 0x2b, 0x95, 0x18, 0x8c, 0x52, 0xb9, 0x78, 0xc2, 0x53, 0x33, 0xcb, 0x4b, 0x61, 0x96, 0x85,
	0x72, 0xb1, 0x80, 0x02, 0x4e, 0x48, 0x05, 0xa7, 0x11, 0x48, 0x41, 0x2f, 0xa5, 0x4a, 0x40, 0x15,
	0xcc, 0x9a, 0x24, 0x36, 0x70, 0x94, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x7e, 0x7b,
	0x11, 0xe2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KaixinServiceClient is the client API for KaixinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KaixinServiceClient interface {
	Kaixin(ctx context.Context, in *KaixinRequest, opts ...grpc.CallOption) (*KaixinResponse, error)
}

type kaixinServiceClient struct {
	cc *grpc.ClientConn
}

func NewKaixinServiceClient(cc *grpc.ClientConn) KaixinServiceClient {
	return &kaixinServiceClient{cc}
}

func (c *kaixinServiceClient) Kaixin(ctx context.Context, in *KaixinRequest, opts ...grpc.CallOption) (*KaixinResponse, error) {
	out := new(KaixinResponse)
	err := c.cc.Invoke(ctx, "/aimgo.passport.http2.v1.KaixinService/Kaixin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KaixinServiceServer is the server API for KaixinService service.
type KaixinServiceServer interface {
	Kaixin(context.Context, *KaixinRequest) (*KaixinResponse, error)
}

// UnimplementedKaixinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKaixinServiceServer struct {
}

func (*UnimplementedKaixinServiceServer) Kaixin(ctx context.Context, req *KaixinRequest) (*KaixinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kaixin not implemented")
}

func RegisterKaixinServiceServer(s *grpc.Server, srv KaixinServiceServer) {
	s.RegisterService(&_KaixinService_serviceDesc, srv)
}

func _KaixinService_Kaixin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KaixinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaixinServiceServer).Kaixin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimgo.passport.http2.v1.KaixinService/Kaixin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaixinServiceServer).Kaixin(ctx, req.(*KaixinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KaixinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aimgo.passport.http2.v1.KaixinService",
	HandlerType: (*KaixinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kaixin",
			Handler:    _KaixinService_Kaixin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaixin.proto",
}

// WeiwuServiceClient is the client API for WeiwuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeiwuServiceClient interface {
	Haha(ctx context.Context, in *HahaRequest, opts ...grpc.CallOption) (*HahaResponse, error)
}

type weiwuServiceClient struct {
	cc *grpc.ClientConn
}

func NewWeiwuServiceClient(cc *grpc.ClientConn) WeiwuServiceClient {
	return &weiwuServiceClient{cc}
}

func (c *weiwuServiceClient) Haha(ctx context.Context, in *HahaRequest, opts ...grpc.CallOption) (*HahaResponse, error) {
	out := new(HahaResponse)
	err := c.cc.Invoke(ctx, "/aimgo.passport.http2.v1.WeiwuService/Haha", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeiwuServiceServer is the server API for WeiwuService service.
type WeiwuServiceServer interface {
	Haha(context.Context, *HahaRequest) (*HahaResponse, error)
}

// UnimplementedWeiwuServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWeiwuServiceServer struct {
}

func (*UnimplementedWeiwuServiceServer) Haha(ctx context.Context, req *HahaRequest) (*HahaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Haha not implemented")
}

func RegisterWeiwuServiceServer(s *grpc.Server, srv WeiwuServiceServer) {
	s.RegisterService(&_WeiwuService_serviceDesc, srv)
}

func _WeiwuService_Haha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HahaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeiwuServiceServer).Haha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimgo.passport.http2.v1.WeiwuService/Haha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeiwuServiceServer).Haha(ctx, req.(*HahaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeiwuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aimgo.passport.http2.v1.WeiwuService",
	HandlerType: (*WeiwuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Haha",
			Handler:    _WeiwuService_Haha_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaixin.proto",
}
