// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kaixin.proto

package aimgo_passport_http2_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _kaixin_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on HahaRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *HahaRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	return nil
}

// HahaRequestValidationError is the validation error returned by
// HahaRequest.Validate if the designated constraints aren't met.
type HahaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HahaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HahaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HahaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HahaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HahaRequestValidationError) ErrorName() string { return "HahaRequestValidationError" }

// Error satisfies the builtin error interface
func (e HahaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHahaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HahaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HahaRequestValidationError{}

// Validate checks the field values on HahaResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *HahaResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Msg

	// no validation rules for Data

	return nil
}

// HahaResponseValidationError is the validation error returned by
// HahaResponse.Validate if the designated constraints aren't met.
type HahaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HahaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HahaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HahaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HahaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HahaResponseValidationError) ErrorName() string { return "HahaResponseValidationError" }

// Error satisfies the builtin error interface
func (e HahaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHahaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HahaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HahaResponseValidationError{}

// Validate checks the field values on KaixinRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *KaixinRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	return nil
}

// KaixinRequestValidationError is the validation error returned by
// KaixinRequest.Validate if the designated constraints aren't met.
type KaixinRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KaixinRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KaixinRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KaixinRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KaixinRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KaixinRequestValidationError) ErrorName() string { return "KaixinRequestValidationError" }

// Error satisfies the builtin error interface
func (e KaixinRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKaixinRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KaixinRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KaixinRequestValidationError{}

// Validate checks the field values on KaixinResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *KaixinResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Msg

	// no validation rules for Data

	return nil
}

// KaixinResponseValidationError is the validation error returned by
// KaixinResponse.Validate if the designated constraints aren't met.
type KaixinResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KaixinResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KaixinResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KaixinResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KaixinResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KaixinResponseValidationError) ErrorName() string { return "KaixinResponseValidationError" }

// Error satisfies the builtin error interface
func (e KaixinResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKaixinResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KaixinResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KaixinResponseValidationError{}
