// Code generated by protoc-gen-go. DO NOT EDIT.
// source: say.proto

package aimgo_passport_http2_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Eplat int32

const (
	//	开发心
	Eplat_EPLAT_UNSPECIFIED Eplat = 0
	Eplat_EPLAT_UNKNOWN     Eplat = 1
	Eplat_EPLAT_WEB         Eplat = 2
	Eplat_EPLAT_M           Eplat = 3
	Eplat_EPLAT_ANDROID     Eplat = 4
	Eplat_EPLAT_IOS         Eplat = 5
)

var Eplat_name = map[int32]string{
	0: "EPLAT_UNSPECIFIED",
	1: "EPLAT_UNKNOWN",
	2: "EPLAT_WEB",
	3: "EPLAT_M",
	4: "EPLAT_ANDROID",
	5: "EPLAT_IOS",
}

var Eplat_value = map[string]int32{
	"EPLAT_UNSPECIFIED": 0,
	"EPLAT_UNKNOWN":     1,
	"EPLAT_WEB":         2,
	"EPLAT_M":           3,
	"EPLAT_ANDROID":     4,
	"EPLAT_IOS":         5,
}

func (x Eplat) String() string {
	return proto.EnumName(Eplat_name, int32(x))
}

func (Eplat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6dad255d0361606e, []int{0}
}

type HelloRequest struct {
	//	请求名称
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dad255d0361606e, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*Data  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dad255d0361606e, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HelloResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *HelloResponse) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dad255d0361606e, []int{2}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dad255d0361606e, []int{3}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Data struct {
	Plat                 Eplat                `protobuf:"varint,1,opt,name=plat,proto3,enum=aimgo.passport.http2.v1.Eplat" json:"plat,omitempty"`
	Confmsg              string               `protobuf:"bytes,2,opt,name=confmsg,proto3" json:"confmsg,omitempty"`
	OrderTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dad255d0361606e, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetPlat() Eplat {
	if m != nil {
		return m.Plat
	}
	return Eplat_EPLAT_UNSPECIFIED
}

func (m *Data) GetConfmsg() string {
	if m != nil {
		return m.Confmsg
	}
	return ""
}

func (m *Data) GetOrderTime() *timestamp.Timestamp {
	if m != nil {
		return m.OrderTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("aimgo.passport.http2.v1.Eplat", Eplat_name, Eplat_value)
	proto.RegisterType((*HelloRequest)(nil), "aimgo.passport.http2.v1.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "aimgo.passport.http2.v1.HelloResponse")
	proto.RegisterType((*UpdateRequest)(nil), "aimgo.passport.http2.v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "aimgo.passport.http2.v1.UpdateResponse")
	proto.RegisterType((*Data)(nil), "aimgo.passport.http2.v1.Data")
}

func init() { proto.RegisterFile("say.proto", fileDescriptor_6dad255d0361606e) }

var fileDescriptor_6dad255d0361606e = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x9b, 0x26, 0x69, 0xc9, 0x9c, 0x29, 0xe9, 0x80, 0x18, 0x02, 0xea, 0x11, 0x51, 0x0f,
	0x1f, 0xb6, 0x34, 0x82, 0xe0, 0x63, 0x35, 0x11, 0x83, 0x9a, 0x2b, 0x49, 0x4b, 0x05, 0x1f, 0xca,
	0xf6, 0xb2, 0x4d, 0x0f, 0x92, 0xdb, 0x35, 0xbb, 0x3d, 0xb8, 0x4f, 0xe1, 0x87, 0xf2, 0x8b, 0x49,
	0x36, 0x86, 0xd3, 0x87, 0x78, 0xf8, 0x36, 0xb3, 0xfc, 0x66, 0xe6, 0xcf, 0xff, 0xbf, 0xe0, 0x48,
	0xba, 0x21, 0xa2, 0xe5, 0x8a, 0xe3, 0x23, 0xba, 0x6c, 0x2a, 0x4e, 0x04, 0x95, 0x52, 0xf0, 0x56,
	0x91, 0x3b, 0xa5, 0x44, 0x44, 0xd6, 0xa7, 0xc1, 0xd3, 0x8a, 0xf3, 0xaa, 0x66, 0x27, 0x1a, 0xbb,
	0xb9, 0xbf, 0x3d, 0x51, 0xcb, 0x86, 0x49, 0x45, 0x1b, 0xd1, 0x4f, 0x86, 0x21, 0x3c, 0xf8, 0xc8,
	0xea, 0x9a, 0xe7, 0xec, 0xfb, 0x3d, 0x93, 0x0a, 0x11, 0xac, 0x15, 0x6d, 0x98, 0x6f, 0x4c, 0x8d,
	0x99, 0x93, 0xeb, 0x3a, 0xbc, 0x03, 0xf7, 0x37, 0x23, 0x05, 0x5f, 0x49, 0xd6, 0x41, 0x0b, 0x5e,
	0xf6, 0x90, 0x9d, 0xeb, 0x1a, 0x3d, 0x30, 0x1b, 0x59, 0xf9, 0xfb, 0x7a, 0xae, 0x2b, 0xf1, 0x14,
	0xac, 0x92, 0x2a, 0xea, 0x9b, 0x53, 0x73, 0x36, 0x89, 0x1e, 0x93, 0x11, 0x8d, 0x24, 0xa6, 0x8a,
	0xe6, 0x1a, 0x0d, 0x9f, 0x81, 0x7b, 0x29, 0x4a, 0xaa, 0xd8, 0xbf, 0xe4, 0xbc, 0x81, 0xa3, 0x01,
	0xfa, 0x1f, 0x3d, 0xe1, 0x0f, 0x03, 0xac, 0xee, 0x16, 0x46, 0x60, 0x89, 0x9a, 0x2a, 0x8d, 0x1f,
	0x45, 0x4f, 0x46, 0x85, 0x25, 0x1d, 0x95, 0x6b, 0x16, 0x7d, 0x38, 0x5c, 0xf0, 0xd5, 0xed, 0x76,
	0xe5, 0xd0, 0xe2, 0x5b, 0x00, 0xde, 0x96, 0xac, 0xbd, 0xee, 0xac, 0xf5, 0xcd, 0xa9, 0x31, 0x9b,
	0x44, 0x01, 0xe9, 0x7d, 0x27, 0x83, 0xef, 0xe4, 0x62, 0xf0, 0x3d, 0x77, 0x34, 0xdd, 0xf5, 0xaf,
	0x38, 0xd8, 0xfa, 0x06, 0x3e, 0x84, 0xe3, 0xe4, 0xfc, 0xf3, 0xd9, 0xc5, 0xf5, 0x65, 0x56, 0x9c,
	0x27, 0xef, 0xd3, 0x0f, 0x69, 0x12, 0x7b, 0x7b, 0x78, 0x0c, 0xee, 0xf0, 0xfc, 0x29, 0x9b, 0x5f,
	0x65, 0x9e, 0x81, 0x2e, 0x38, 0xfd, 0xd3, 0x55, 0xf2, 0xce, 0xdb, 0xc7, 0x09, 0x1c, 0xf6, 0xed,
	0x17, 0xcf, 0xdc, 0xe2, 0x67, 0x59, 0x9c, 0xcf, 0xd3, 0xd8, 0xb3, 0xb6, 0x78, 0x3a, 0x2f, 0x3c,
	0x3b, 0xfa, 0x69, 0x00, 0x14, 0x74, 0x53, 0xb0, 0x76, 0xbd, 0x5c, 0x30, 0xfc, 0x0a, 0xb6, 0x0e,
	0x16, 0x9f, 0x8f, 0x7a, 0xf0, 0xe7, 0xe7, 0x08, 0x5e, 0xec, 0xc2, 0xfa, 0x3c, 0xc2, 0x3d, 0xfc,
	0x06, 0x07, 0x7d, 0x46, 0x38, 0x3e, 0xf3, 0x57, 0xd2, 0xc1, 0xcb, 0x9d, 0xdc, 0xb0, 0xfc, 0xe6,
	0x40, 0xbb, 0xfa, 0xfa, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x9d, 0x61, 0xf8, 0x01, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SayServiceClient is the client API for SayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SayServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type sayServiceClient struct {
	cc *grpc.ClientConn
}

func NewSayServiceClient(cc *grpc.ClientConn) SayServiceClient {
	return &sayServiceClient{cc}
}

func (c *sayServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/aimgo.passport.http2.v1.SayService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/aimgo.passport.http2.v1.SayService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayServiceServer is the server API for SayService service.
type SayServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedSayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSayServiceServer struct {
}

func (*UnimplementedSayServiceServer) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedSayServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterSayServiceServer(s *grpc.Server, srv SayServiceServer) {
	s.RegisterService(&_SayService_serviceDesc, srv)
}

func _SayService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimgo.passport.http2.v1.SayService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SayService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimgo.passport.http2.v1.SayService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aimgo.passport.http2.v1.SayService",
	HandlerType: (*SayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _SayService_Hello_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SayService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "say.proto",
}
