// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: say.proto

package aimgo_passport_http2_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SayService service

type SayService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
}

type sayService struct {
	c    client.Client
	name string
}

func NewSayService(name string, c client.Client) SayService {
	return &sayService{
		c:    c,
		name: name,
	}
}

func (c *sayService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "SayService.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "SayService.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SayService service

type SayServiceHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
}

func RegisterSayServiceHandler(s server.Server, hdlr SayServiceHandler, opts ...server.HandlerOption) error {
	type sayService interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
	}
	type SayService struct {
		sayService
	}
	h := &sayServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SayService{h}, opts...))
}

type sayServiceHandler struct {
	SayServiceHandler
}

func (h *sayServiceHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.SayServiceHandler.Hello(ctx, in, out)
}

func (h *sayServiceHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.SayServiceHandler.Update(ctx, in, out)
}
